name: Emulated Targets Build

on:
  push:
    branches: [ main, ocp-tiogapass/main ]
  pull_request:
    branches: [ main, ocp-tiogapass/main ]
  workflow_dispatch:

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_TOKEN }}
          ec2-image-id: ami-0c3e8d77d801745a3
          ec2-instance-type: c5.2xlarge
          subnet-id: subnet-35b25178
          security-group-id: sg-0d7007f6ff763c3bd

  build-evb-ast2500:
    runs-on: ${{ needs.start-runner.outputs.label }}
    needs: start-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build EVB AST2500
        uses: ./.github/actions/build-emulated
        with:
          target: evb-ast2500

  build-evb-ast2600:
    runs-on: ${{ needs.start-runner.outputs.label }}
    needs: start-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build EVB AST2600
        uses: ./.github/actions/build-emulated
        with:
          target: evb-ast2600

  build-fvp:
    runs-on: ${{ needs.start-runner.outputs.label }}
    needs: start-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build FVP
        uses: ./.github/actions/build-emulated
        with:
          target: fvp

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - build-evb-ast2500
      - build-evb-ast2600
      - build-fvp
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
